
services:

  # ── MinIO (Data Lake) ──
  minio:
    image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"    # API S3
      - "9001:9001"    # Console Web
    volumes:
      - minio-data:/data

volumes:
  minio-data: